### ISSUE TITLE
mirror update issue

### ISSUE THREAD

**Issue by Amu757** [vhqtvn/VHEditor-Android#101]
unable to update terminal mirros so pkg install command and other commands also not working

**Comment by manyang-megantoro** [comment]
I get this problem also, please update

**Comment by Adless-i** [comment]
use this $ apt update

don't use 
$ apt upgrade
$ pkg update
$ pkg upgrade

**Comment by D4RKFIR9** [comment]
It's impossible to update and it keeps giving errors all the time!

**Comment by vhqtvn** [comment]
Currently packages are uploading to github releases of forked termux-packages repo:

https://github.com/vhqtvn/termux-packages/releases

My webserver only send redirection to the release url, that url will be redirected to aws with argument signature checking, but then current apt replaced `%1F` in that final url into `/` and aws just validate the raw get parameters instead so the sig become invalid, that's why downloads failed.

In order to fix that i'll need to patch apt download module so that it dont normalize '%1F', or create an in-app proxy so that that proxy can rewrite '/' back into '%2F', i dont have time for other projects recently so helps are welcome!

**Comment by vhqtvn** [comment]
That problem caused the issues #102, #100 and #97 too.

**Comment by vhqtvn** [comment]
Fixed in latest version.
