### ISSUE TITLE
Browser Preview not working

### ISSUE THREAD

**Issue by SK435** [vhqtvn/VHEditor-Android#54]
@vhqtvn 
![Screenshot_20210608-110121_1623142830117.jpg](https://user-images.githubusercontent.com/76910195/121156592-73cd8400-c866-11eb-838f-274ca85673dc.jpg)
Whenever I try to open my html file in live server and to do do live browser preview on my Android mobile version 9
It shows this
Any one please solve this problem I am doing it in vscode when I am opening browser preview of my code it is showing this 
"no chrome installation found, or no chrome executable set in the settings - used path null"

Please help me how to Fix this error .

**Comment by sopyb** [comment]
![image](https://user-images.githubusercontent.com/32602702/136011233-d447d260-9dc6-45c8-851c-4bd8dee90f21.png)

Can reproduce on desktop VSCode, the issue is extension related rather than a code-server or VH-Editor one. 
[The extension](https://marketplace.visualstudio.com/items?itemName=auchenberg.vscode-browser-preview) is deprecated so theres a high probabiliy this will never be fixed.
