### ISSUE TITLE
apt update not working

### ISSUE THREAD

**Issue by jhmaster2000** [vhqtvn/VHEditor-Android#69]
Just installed the app on Android 11, through GitHub releases as instructed. (ARM64 A72) 

Tried to apt install node-lts, didnt work.
Remembered apt update was needed first on first runs, so i ran it but it also errored:
![Screenshot_20210814-200145_VHEditor](https://user-images.githubusercontent.com/32803471/129462333-f4253fe2-d796-4973-b298-3e7ded9a70fb.jpg)

Not sure what to do next

**Comment by CharlesForson** [comment]
@jhmaster2000, similar problem, thought it was the 2 .list files in apt.conf.d, so I deleted and ran apt update again, which did complete the update, but I still couldn't apt upgrade.I tried termux-change-repo to Albatross (mentality.rip) because I was getting a permission denied error, which seemed to work around the permissions error, but now apt/pkg isn't locating all the really awesome but disabled packages in vhqtvn's fork. 

@vhqtvn these minor hiccups aside, you've done an outstanding job on this! thanks in advance for any pointers and thank you for sharing this!

**Comment by CharlesForson** [comment]
@vhqtvn CORRECTION: not necessarily a hiccup on your end, my sincere apologies (for my part, probably user error). Didn't meant to work from that supposition.

**Comment by vhqtvn** [comment]
@jhmaster2000 you should install nodejs, not node, only the main repository is ported now so other things (games, science etc) will result in error, just ignore them.

@CharlesForson np, great you got it working.

**Comment by jhmaster2000** [comment]
> @jhmaster2000 you should install nodejs, not node, only the main repository is ported now so other things (games, science etc) will result in error, just ignore them.
> 
> @CharlesForson np, great you got it working.

oh interesting, indeed `apt install nodejs` worked, it successfully installed it, but for some reason it cant invoke the commands? I've tried restarting the app with no luck:
![SmartSelect_20210816-122047_VHEditor](https://user-images.githubusercontent.com/32803471/129656891-539db4c7-4ea8-439e-ae37-f28bdb2ee333.jpg)

**Comment by vhqtvn** [comment]
Please try to install again with libicu

```
apt update
apt install nodejs libicu
```

Reopen the issue if the problem still occurs.
